.TH "ANIME-COLORSCRIPTS" "1" "2021-08-20" "GNU" "User Commands"

.SH "NAME"
.PP
anime-colorscripts - display unicode sprites of anime in the terminal

.SH "SYNOPSIS"
.PP
.B anime-colorscripts
.RB [-h|--help|help]
.RB [-l|--list|list]
.RB [-r|--random|random
.IR generation ]
.RB [-n|--name
.IR name]

.SH "DESCRIPTION"
.PP
Anime-colorscripts is a CLI utility written in shell script that prints out
unicode sprites of anime to the terminal. Almost all anime generations 1-8
are available (except may be shiny anime or different forms). You can select
specific anime to be printed out by name or let the script choose a anime
randomly. While choosing randomly you can also filter by generation.

.SH "OPTIONS"
.TP
.B "-h, --help, help"
Print help.
.TP
.B "-l, --list, list"
List all available anime.
.TP
\fB -r, --random, random\fR \fI generation\fR
Select a anime at random and print it out. Can be followed by an optional
generation number or range 1-8 to print out random anime from a specific
generation or range of generations.
If no generation is specified, selects from full list of available anime.
.TP
\fB -n, --name\fR \fI name\fR
Select a specific anime to print out by name. Most anime are spelled as
expected. A few anime with some special characters in their names might be spelled
slightly differently. Examples nidoran-f,nidoran-m,farfetchd,mr-mime etc. You can
check the output of the\fB list\fR option if in doubt.

.SH "FILES"
.TP
All the files are present in the directory
"/usr/local/opt/anime-colorscripts"
.TP
with the executable script being symlinked to
"/usr/local/bin/anime-colorscripts"

.SH "EXAMPLES"
.SS "anime-colorscripts -r"
.PP
Prints out a random anime. Add this command to your shell config file (.bashrc, .zshrc, fish.config
etc.) to print out a random anime every time you open the terminal.
.SS "anime-colorscripts -r 1"
.PP
Print out a random anime from generation 1.
.SS "anime-colorscripts -r 1-3"
.PP
Print out a random anime from generations 1-3.
.SS "anime-colorscripts -r 1 3 6"
.PP
Print out a random anime from generations 1,3 or 6.
.SS "anime-colorscripts -l"
.PP
Print out all available anime names.
.SS "anime-colorscripts -n chikorita"
.PP
Print out the anime chikorita.

