
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Setup python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      
      - name: Setup PIP
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            bs4
            scikit-image
            numpy

      - name: Scrape link
      - run: python src/generator/chara_list.py

      - name: Scrape Image
      - run: bash ./scripts/scrape.sh

      - name: Generate Art
      - run: python src/generator/make_art.py
      - run: rm -rf images

      - name: Setup Tar and Archiving
      - run: mkdir -p acscript/anime-colorscripts
      - run: cp LICENSE acscript/anime-colorscripts
      - run: cp anime-colorscripts.sh acscript/anime-colorscripts
      - run: cp charalist.txt acscript/anime-colorscripts
      - run: cp install.sh acscript/anime-colorscripts
      - run: cp -r colorscripts acscript/anime-colorscripts
      - run: tar -czvf anime-colorscripts.tar.gz -C acscript .
      - uses: marvinpinto/action-automatic-releases@latest
        with: 
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            anime-colorscripts.tar.gz

